# Generated by Django 5.1.5 on 2026-09-11 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('target_model', models.CharField(max_length=60)),
                ('target_id', models.BigIntegerField()),
                ('field', models.CharField(max_length=60)),
                ('old_value', models.CharField(max_length=200)),
                ('new_value', models.CharField(max_length=200)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='shops.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tuzatish',
                'verbose_name_plural': 'Tuzatishlar',
            },
        ),
        migrations.CreateModel(
            name='DailyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('computed_sales', models.BigIntegerField(default=0, verbose_name='Hisoblangan savdo')),
                ('entered_sales', models.BigIntegerField(default=0, verbose_name='Kiritilgan savdo')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closes', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Kun yakuni',
                'verbose_name_plural': 'Kun yakunlari',
                'unique_together': {('shop', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyCloseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('morning_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('evening_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit_price', models.BigIntegerField(default=0)),
                ('close', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.dailyclose')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Xaridor')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('amount', models.BigIntegerField(default=0, verbose_name="Summa (so'm)")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Nasiya',
                'verbose_name_plural': 'Nasiyalar',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('mode', models.CharField(choices=[('scan', 'Skaner'), ('quick', 'Tez')], default='quick', max_length=8, verbose_name='Rejim')),
                ('subtotal', models.BigIntegerField(default=0, verbose_name='Oraliq summa')),
                ('discount', models.BigIntegerField(default=0, verbose_name='Chegirma')),
                ('rounding', models.BigIntegerField(default=0, verbose_name='Yaxlitlash')),
                ('total', models.BigIntegerField(default=0, verbose_name="Jami (so'm)")),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma")], default='cash', max_length=12, verbose_name="To'lov")),
                ('is_wholesale', models.BooleanField(default=False, verbose_name='Ulgurji')),
                ('client_ts', models.DateTimeField(blank=True, null=True, verbose_name='Qurilma vaqti')),
                ('is_late', models.BooleanField(default=False, verbose_name='Kech kiritilgan')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Miqdor')),
                ('unit_price', models.BigIntegerField(default=0, verbose_name="Narx (so'm)")),
                ('line_total', models.BigIntegerField(default=0, verbose_name='Qator jami')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='catalog.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('amount', models.BigIntegerField(default=0, verbose_name="Summa (so'm)")),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Sabab')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.sale')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Qaytarish',
                'verbose_name_plural': 'Qaytarishlar',
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor')),
                ('in_packs', models.BooleanField(default=False, verbose_name='Qopda')),
                ('unit_price', models.BigIntegerField(default=0, verbose_name="Kelish narxi (so'm)")),
                ('source', models.CharField(default='manual', max_length=30, verbose_name='Manba')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='catalog.product')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Miqdor')),
                ('photo', models.ImageField(upload_to='writeoffs/%Y/%m/', verbose_name='Foto')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Sabab')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeoffs', to='catalog.product')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Hisobdan chiqarish',
                'verbose_name_plural': 'Hisobdan chiqarishlar',
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shop', '-created_at'], name='sales_sale_shop_id_c10bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-created_at'], name='sales_sale_created_66311a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockin',
            index=models.Index(fields=['shop', '-created_at'], name='sales_stock_shop_id_daac19_idx'),
        ),
    ]
