# Generated by Django 5.1.5 on 2026-09-11 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('shops', '0002_shop_latitude_shop_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('expected_cash', models.BigIntegerField(default=0, verbose_name="Kutilgan naqd (so'm)")),
                ('counted_cash', models.BigIntegerField(default=0, verbose_name="Sanalgan naqd (so'm)")),
                ('card_total', models.BigIntegerField(default=0, verbose_name="Karta (so'm)")),
                ('transfer_total', models.BigIntegerField(default=0, verbose_name="O'tkazma (so'm)")),
                ('checks_count', models.PositiveIntegerField(default=0, verbose_name='Cheklar soni')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_closes', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Kassa yopish',
                'verbose_name_plural': 'Kassa yopishlar',
                'indexes': [models.Index(fields=['shop', '-date'], name='sales_regis_shop_id_d4fb93_idx')],
                'unique_together': {('shop', 'date')},
            },
        ),
    ]
