# Generated by Django 5.1.5 on 2026-09-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_registerclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Qaytarish sanasi'),
        ),
    ]
