# Generated by Django 5.1.5 on 2026-09-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_unit_and_more'),
        ('sales', '0003_debt_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Miqdor'),
        ),
    ]
