# Generated by Django 5.1.5 on 2026-09-24 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salereturn_product_salereturn_quantity'),
        ('shops', '0003_shop_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_uid',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Qurilma ID'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uid', ''), _negated=True), fields=('shop', 'client_uid'), name='uniq_sale_shop_client_uid'),
        ),
    ]
