# Generated by Django 5.1.5 on 2026-09-24 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def paid_debts_full(apps, schema_editor):
    """Avval "To'landi" deb belgilangan nasiyalar — to'liq to'langan (qoldiq 0)."""
    Debt = apps.get_model("sales", "Debt")
    Debt.objects.filter(is_paid=True).update(paid_amount=models.F("amount"))


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_client_uid'),
        ('shops', '0003_shop_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='paid_amount',
            field=models.BigIntegerField(default=0, verbose_name="To'langan qismi (so'm)"),
        ),
        migrations.AddField(
            model_name='debt',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_records', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='registerclose',
            name='debt_cash_in',
            field=models.BigIntegerField(default=0, verbose_name="Nasiyadan qaytgan naqd (so'm)"),
        ),
        migrations.AddField(
            model_name='registerclose',
            name='opening_cash',
            field=models.BigIntegerField(default=0, verbose_name="Ertalabki maydalik (so'm)"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('debt', 'Nasiya')], default='cash', max_length=12, verbose_name="To'lov"),
        ),
        migrations.CreateModel(
            name='CashOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('amount', models.BigIntegerField(default=0, verbose_name="Maydalik (so'm)")),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_opens', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Kun boshi maydaligi',
                'verbose_name_plural': 'Kun boshi maydaliklari',
                'unique_together': {('shop', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('amount', models.BigIntegerField(verbose_name="Summa (so'm)")),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma")], default='cash', max_length=12, verbose_name="To'lov")),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.debt')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_payments', to='shops.shop')),
            ],
            options={
                'verbose_name': "Nasiya to'lovi",
                'verbose_name_plural': "Nasiya to'lovlari",
                'indexes': [models.Index(fields=['shop', '-created_at'], name='sales_debtp_shop_id_dc6598_idx')],
            },
        ),
        migrations.RunPython(paid_debts_full, migrations.RunPython.noop),
    ]
