# Generated by Django 5.1.5 on 2026-09-25 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_unit_and_more'),
        ('sales', '0006_debt_paid_amount_debt_sale_and_more'),
        ('shops', '0003_shop_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opening', "Boshlang'ich qoldiq"), ('in', 'Kirim'), ('sale', 'Sotuv'), ('writeoff', 'Hisobdan chiqarish'), ('return', 'Qaytarish'), ('count', 'Sanoq (kun yakuni)')], max_length=10, verbose_name='Tur')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name="O'zgarish")),
                ('balance', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Qoldiq (keyin)')),
                ('unit_price', models.BigIntegerField(default=0, verbose_name="Narx (o'sha payt)")),
                ('ref', models.CharField(blank=True, max_length=60, verbose_name='Hujjat')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Vaqt')),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='catalog.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='shops.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tovar harakati',
                'verbose_name_plural': 'Tovar harakatlari jurnali',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['shop', 'created_at'], name='sales_stock_shop_id_24af11_idx'), models.Index(fields=['product', 'created_at'], name='sales_stock_product_9dd7ea_idx')],
            },
        ),
    ]
