# Generated by Django 5.1.5 on 2026-09-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_stockmove_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclose',
            name='photo',
            field=models.ImageField(blank=True, upload_to='closes/%Y/%m/', verbose_name='Rasta fotosi'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='invoice_photo',
            field=models.ImageField(blank=True, upload_to='stockins/%Y/%m/', verbose_name='Nakladnoy fotosi'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Yetkazib beruvchi'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='supplier_stir',
            field=models.CharField(blank=True, max_length=15, verbose_name='Yetkazib beruvchi STIR'),
        ),
    ]
