# Generated by Django 5.1.5 on 2026-09-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_alert_kind'),
        ('sales', '0009_dailyclose_photo_stockin_invoice_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='public_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ReceiptReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('paid_amount', models.BigIntegerField(verbose_name="Xaridor to'lagan (so'm)")),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='analytics.alert')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_report', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Xaridor xabari',
                'verbose_name_plural': 'Xaridor xabarlari',
            },
        ),
    ]
