# Generated by Django 5.1.5 on 2026-09-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_public_code_receiptreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='sms_remind',
            field=models.BooleanField(default=True, verbose_name='Xaridorga SMS eslatma'),
        ),
    ]
