# Generated by Django 5.2.17 on 2026-10-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_shop_category_buyer_ratio"),
        ("accounts", "0007_clear_own_visible_passwords"),
        ("sales", "0011_debt_sms_remind"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Yaratilgan")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Yangilangan")),
                ("counted_qty", models.DecimalField(decimal_places=3, max_digits=12, verbose_name="Topilgan qoldiq")),
                ("reason", models.CharField(max_length=300, verbose_name="Sabab")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_adjustments", to="catalog.product", verbose_name="Mahsulot")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_adjustments", to="accounts.user", verbose_name="Kiritgan foydalanuvchi")),
            ],
            options={
                "verbose_name": "Qoldiq tuzatishi",
                "verbose_name_plural": "Qoldiq tuzatishlari",
                "ordering": ["-created_at"],
            },
        ),
    ]
