# Generated by Django 5.1.5 on 2026-09-10 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraTamperEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Vaqt')),
                ('kind', models.CharField(choices=[('covered', "Yopilgan/to'silgan"), ('moved', 'Burilgan/siljigan'), ('offline', "O'chib qolgan"), ('blurred', 'Xiralashgan')], max_length=20, verbose_name='Turi')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Davomiyligi (sek)')),
                ('clip', models.FileField(blank=True, upload_to='tamper_clips/', verbose_name='Video dalil')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamper_events', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Kamera buzilishi',
                'verbose_name_plural': 'Kamera buzilishlari',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Summa (so'm)")),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Sabab')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='markets.shop')),
            ],
            options={
                'verbose_name': 'Qaytarish',
                'verbose_name_plural': 'Qaytarishlar',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Summa (so'm)")),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma")], default='cash', max_length=12, verbose_name="To'lov turi")),
                ('is_wholesale', models.BooleanField(default=False, verbose_name='Ulgurji')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='markets.shop')),
            ],
            options={
                'verbose_name': 'Savdo',
                'verbose_name_plural': 'Savdolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Mahsulot')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Miqdor')),
                ('unit', models.CharField(default='dona', max_length=20, verbose_name='Birlik')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Narx (so'm)")),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Vaqt')),
                ('product_guess', models.CharField(blank=True, max_length=120, verbose_name='Taxminiy mahsulot')),
                ('confidence', models.FloatField(default=0, verbose_name='Ishonch')),
                ('clip', models.FileField(blank=True, upload_to='sale_clips/', verbose_name='Video klip')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='cameras.camera')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='markets.shop')),
            ],
            options={
                'verbose_name': 'AI sotuv kuzatuvi',
                'verbose_name_plural': 'AI sotuv kuzatuvlari',
            },
        ),
        migrations.CreateModel(
            name='StockWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product_name', models.CharField(max_length=150, verbose_name='Mahsulot')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Miqdor')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Birlik')),
                ('photo', models.ImageField(upload_to='writeoffs/', verbose_name='Foto (majburiy)')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Sabab')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeoffs', to='markets.shop')),
            ],
            options={
                'verbose_name': 'Hisobdan chiqarish',
                'verbose_name_plural': 'Hisobdan chiqarishlar',
            },
        ),
        migrations.CreateModel(
            name='CustomerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Vaqt')),
                ('dwell_seconds', models.PositiveIntegerField(default=0, verbose_name="To'xtash (sek)")),
                ('track_id', models.CharField(blank=True, max_length=64)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='cameras.camera')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='markets.shop')),
            ],
            options={
                'verbose_name': 'Xaridor tashrifi',
                'verbose_name_plural': 'Xaridor tashriflari',
                'indexes': [models.Index(fields=['shop', 'timestamp'], name='events_cust_shop_id_2d1059_idx')],
            },
        ),
    ]
