# Generated by Django 5.1.5 on 2026-09-10 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='Viloyat/tuman')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bozor',
                'verbose_name_plural': 'Bozorlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nomi')),
                ('avg_ticket', models.DecimalField(decimal_places=2, default=0, help_text="Halol do'konlar bo'yicha kalibrlangan o'rtacha savdo", max_digits=12, verbose_name="O'rtacha chek (so'm)")),
                ('waste_norm_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name="Chirish me'yori (%)")),
            ],
            options={
                'verbose_name': 'Mahsulot toifasi',
                'verbose_name_plural': 'Mahsulot toifalari',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Do'kon nomi")),
                ('stir', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='STIR (soliq raqami)')),
                ('owner_name', models.CharField(blank=True, max_length=200, verbose_name='Egasi (F.I.O.)')),
                ('owner_phone', models.CharField(blank=True, max_length=20, verbose_name='Egasi telefoni')),
                ('row_label', models.CharField(blank=True, max_length=60, verbose_name='Qator/joy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('closed_weekdays', models.CharField(blank=True, help_text="Vergul bilan: 0=Du ... 6=Ya. Masalan '6' = yakshanba yopiq", max_length=20, verbose_name='Yopiq kunlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='markets.productcategory', verbose_name='Toifa')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='markets.market', verbose_name='Bozor')),
            ],
            options={
                'verbose_name': "Do'kon",
                'verbose_name_plural': "Do'konlar",
                'ordering': ['market', 'name'],
            },
        ),
    ]
