# Generated by Django 5.1.5 on 2026-09-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_telegram',
            field=models.BooleanField(default=True, verbose_name='Telegram bildirishnoma'),
        ),
    ]
