# Generated by Django 5.1.5 on 2026-09-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_notify_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visible_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Joriy parol'),
        ),
    ]
