# Generated by Django 5.1.5 on 2026-09-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_visible_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super admin'), ('inspector', 'Tekshiruvchi'), ('seller', 'Sotuvchi'), ('prosecutor', 'Prokuror (kuzatuvchi)')], default='seller', max_length=16, verbose_name='Rol'),
        ),
    ]
