# Generated by Django 5.1.5 on 2026-09-10 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date', models.DateField(verbose_name='Tegishli sana')),
                ('level', models.CharField(choices=[('green', 'Yashil'), ('yellow', 'Sariq'), ('red', 'Qizil')], max_length=10, verbose_name='Daraja')),
                ('message', models.CharField(max_length=300, verbose_name='Sabab')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('assigned', 'Biriktirilgan'), ('resolved', 'Yakunlangan'), ('dismissed', "E'tiborsiz")], default='new', max_length=12, verbose_name='Holat')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Telegram yuborildi')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='markets.shop')),
            ],
            options={
                'verbose_name': 'Ogohlantirish',
                'verbose_name_plural': 'Ogohlantirishlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyShopStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('visitor_count', models.PositiveIntegerField(default=0, verbose_name='Xaridorlar')),
                ('recorded_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Kiritilgan savdo')),
                ('estimated_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='AI taxmini')),
                ('camera_uptime_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Kamera ishlashi (%)')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='markets.shop')),
            ],
            options={
                'verbose_name': 'Kunlik statistika',
                'verbose_name_plural': 'Kunlik statistikalar',
                'ordering': ['-date'],
                'unique_together': {('shop', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('month', models.PositiveIntegerField(verbose_name='Oy')),
                ('declared_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Deklaratsiya (so'm)")),
                ('source', models.CharField(default='excel', max_length=50, verbose_name='Manba')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='markets.shop')),
            ],
            options={
                'verbose_name': 'Deklaratsiya',
                'verbose_name_plural': 'Deklaratsiyalar',
                'unique_together': {('shop', 'year', 'month')},
            },
        ),
    ]
