# Generated by Django 5.1.5 on 2026-09-11 05:28

import apps.cameras.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('visit', 'Xaridor tashrifi'), ('tamper', 'Kamera buzilishi'), ('sale', 'Sotuv kuzatuvi'), ('gate_in', 'Kirim (darvoza)'), ('heartbeat', 'Tiriklik')], max_length=12)),
                ('count', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('clip', models.FileField(blank=True, upload_to='clips/%Y/%m/')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Kamera hodisasi',
                'verbose_name_plural': 'Kamera hodisalari',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi/joyi')),
                ('kind', models.CharField(choices=[('counter', 'Peshtaxta (xaridor sanash)'), ('overview', "Umumiy ko'rinish"), ('gate', 'Darvoza (ANPR/kirim)')], default='counter', max_length=12, verbose_name='Turi')),
                ('rtsp_main', models.CharField(blank=True, max_length=500, verbose_name='RTSP asosiy')),
                ('rtsp_sub', models.CharField(blank=True, max_length=500, verbose_name='RTSP substream')),
                ('counter_zone', models.JSONField(blank=True, default=list, verbose_name='Peshtaxta zonasi')),
                ('staff_zone', models.JSONField(blank=True, default=list, verbose_name='Sotuvchi zonasi')),
                ('token', models.CharField(default=apps.cameras.models.make_token, editable=False, max_length=64, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('tampered', 'Buzilgan')], default='offline', max_length=12)),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi signal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='geo.market', verbose_name='Bozor')),
            ],
            options={
                'verbose_name': 'Kamera',
                'verbose_name_plural': 'Kameralar',
                'ordering': ['market', 'name'],
            },
        ),
    ]
