# Generated by Django 5.1.5 on 2026-09-11 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='shops.shop', verbose_name="Do'kon"),
        ),
        migrations.AddField(
            model_name='cameraevent',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cameras.camera'),
        ),
        migrations.AddField(
            model_name='cameraevent',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_events', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='cameraevent',
            index=models.Index(fields=['shop', 'ts'], name='cameras_cam_shop_id_e08e26_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraevent',
            index=models.Index(fields=['camera', 'ts'], name='cameras_cam_camera__16c4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraevent',
            index=models.Index(fields=['type', 'ts'], name='cameras_cam_type_3f82bd_idx'),
        ),
    ]
