# Generated by Django 5.2.17 on 2026-10-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0002_initial"),
        ("shops", "0004_shop_fiscal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraevent",
            name="type",
            field=models.CharField(
                choices=[("visit", "Xaridor tashrifi"), ("tamper", "Kamera buzilishi"),
                         ("sale", "Sotuv kuzatuvi"), ("product", "Mahsulot kuzatuvi"),
                         ("packaged", "Paketga joylash"), ("gate_in", "Kirim (darvoza)"),
                         ("heartbeat", "Tiriklik")],
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="ProductObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Yaratilgan")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Yangilangan")),
                ("event_id", models.CharField(max_length=64, unique=True, verbose_name="Worker hodisa ID")),
                ("kind", models.CharField(choices=[("product", "Mahsulot kuzatuvi"), ("packaged", "Paketga joylandi")], max_length=12, verbose_name="Kuzatuv turi")),
                ("product_label", models.CharField(max_length=300, verbose_name="Model aniqlagan nom")),
                ("product_code", models.CharField(blank=True, max_length=128, verbose_name="Model aniqlagan kod")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12, verbose_name="Miqdor")),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4, verbose_name="Ishonch")),
                ("started_at", models.DateTimeField(db_index=True, verbose_name="Boshlanish vaqti")),
                ("ended_at", models.DateTimeField(db_index=True, verbose_name="Tugash vaqti")),
                ("review_state", models.CharField(choices=[("pending", "Tekshiruv kerak"), ("confirmed", "Tasdiqlangan"), ("rejected", "Rad etilgan")], default="pending", max_length=12, verbose_name="Tekshiruv holati")),
                ("evidence", models.JSONField(blank=True, default=dict, verbose_name="Dalil")),
                ("camera", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_observations", to="cameras.camera")),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="product_observations", to="shops.shop")),
            ],
            options={"verbose_name": "Mahsulot/paket kuzatuvi", "verbose_name_plural": "Mahsulot/paket kuzatuvlari", "ordering": ["-ended_at", "-id"]},
        ),
        migrations.AddIndex(model_name="productobservation", index=models.Index(fields=["shop", "ended_at"], name="cameras_pro_shop_id_93a930_idx")),
        migrations.AddIndex(model_name="productobservation", index=models.Index(fields=["camera", "ended_at"], name="cameras_pro_camera__f67f45_idx")),
        migrations.AddIndex(model_name="productobservation", index=models.Index(fields=["review_state", "ended_at"], name="cameras_pro_review__ac6649_idx")),
    ]
