# Generated by Django 5.1.5 on 2026-10-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_productobservation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productobservation',
            new_name='cameras_pro_shop_id_109b7b_idx',
            old_name='cameras_pro_shop_id_93a930_idx',
        ),
        migrations.RenameIndex(
            model_name='productobservation',
            new_name='cameras_pro_camera__6607e4_idx',
            old_name='cameras_pro_camera__f67f45_idx',
        ),
        migrations.RenameIndex(
            model_name='productobservation',
            new_name='cameras_pro_review__ac64c2_idx',
            old_name='cameras_pro_review__ac6649_idx',
        ),
    ]
