# Generated by Django 5.1.5 on 2026-09-11 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_threshold', models.PositiveSmallIntegerField(default=80, verbose_name='Yashil chegara')),
                ('yellow_threshold', models.PositiveSmallIntegerField(default=50, verbose_name='Sariq chegara')),
                ('weight_cash', models.PositiveSmallIntegerField(default=35, verbose_name="Kassa og'irligi")),
                ('weight_camera', models.PositiveSmallIntegerField(default=25, verbose_name="Kamera og'irligi")),
                ('weight_stock', models.PositiveSmallIntegerField(default=25, verbose_name="Qoldiq og'irligi")),
                ('weight_price', models.PositiveSmallIntegerField(default=15, verbose_name="Narx og'irligi")),
                ('weakest_part_cap', models.PositiveSmallIntegerField(default=15, verbose_name="Eng zaif qism qo'shimchasi")),
                ('buyer_ratio', models.DecimalField(decimal_places=2, default=0.35, max_digits=4, verbose_name='Xaridorga aylanish ulushi')),
                ('discount_tiers', models.JSONField(default=list, help_text="[[chegara, [t1,t2,t3]], ...] — so'mda", verbose_name='Chegirma jadvali')),
                ('max_discount_no_cost_pct', models.PositiveSmallIntegerField(default=30, verbose_name="Tannarx noma'lum bo'lsa maks chegirma (%)")),
                ('rounding_max', models.PositiveIntegerField(default=1000, verbose_name="Yaxlitlash maksimum (so'm)")),
                ('login_max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='Maks kirish urinishi')),
                ('login_lock_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Blok davomiyligi (daq)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tizim sozlamalari',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('action', models.CharField(choices=[('login', 'Kirish'), ('view', "Ko'rish"), ('export', 'Eksport'), ('write', "O'zgartirish"), ('settings', 'Sozlama')], default='view', max_length=16, verbose_name='Amal')),
                ('method', models.CharField(blank=True, max_length=8)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('interface', models.CharField(blank=True, max_length=16)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit yozuvi',
                'verbose_name_plural': 'Audit jurnali',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_auditl_created_1a76fa_idx'), models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx')],
            },
        ),
    ]
