# Generated by Django 5.1.5 on 2026-09-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='cash_shortage_pct',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Kassa kamomadi chegarasi (%)'),
        ),
    ]
