# Generated by Django 5.1.5 on 2026-09-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='anomaly_drop_pct',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Savdo tushishi chegarasi (%)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tax_rate_percent',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Soliq stavkasi (%)'),
        ),
    ]
