# Generated by Django 5.1.5 on 2026-09-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings_anomaly_drop_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='discount_percents',
            field=models.JSONField(default=list, help_text='[5, 10, 15] — chek summasidan %', verbose_name='Chegirma foizlari'),
        ),
    ]
