# Generated by Django 5.1.5 on 2026-09-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_discount_percents'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='fine_penalty_percent',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Jarima ustamasi (%)'),
        ),
    ]
