# Generated by Django 5.1.5 on 2026-09-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemsettings_fine_penalty_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='stockin_photo_min',
            field=models.PositiveBigIntegerField(default=1000000, verbose_name="Nakladnoy majburiy summa (so'm)"),
        ),
    ]
