# Generated by Django 5.1.5 on 2026-09-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsettings_stockin_photo_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('ok', models.BooleanField(default=False, verbose_name='Muvaffaqiyatli')),
                ('offsite_ok', models.BooleanField(default=False, verbose_name='Tashqariga yuborildi')),
                ('files', models.JSONField(default=list)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Zaxira nusxa',
                'verbose_name_plural': 'Zaxira nusxalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
