# Generated by Django 5.1.5 on 2026-09-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backuplog'),
        ('shops', '0004_shop_fiscal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=480)),
                ('status', models.CharField(choices=[('sent', 'Yuborildi'), ('failed', 'Xato'), ('invalid', "Raqam noto'g'ri")], max_length=10)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_id', models.CharField(blank=True, max_length=80)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shops.shop')),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS jurnali',
                'ordering': ['-created_at'],
            },
        ),
    ]
