# Generated by Django 5.1.5 on 2026-09-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_smsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='require_2fa_staff',
            field=models.BooleanField(default=False, verbose_name='Xodimlarga 2FA majburiy'),
        ),
    ]
