# Generated by Django 5.1.5 on 2026-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_systemsettings_require_2fa_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='writeoff_alert_min',
            field=models.PositiveBigIntegerField(default=200000, verbose_name="Hisobdan chiqarish signali — kamida (so'm)"),
        ),
    ]
