# Generated by Django 5.1.5 on 2026-09-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_systemsettings_writeoff_alert_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='correction_alert_min',
            field=models.PositiveBigIntegerField(default=100000, verbose_name="Tuzatish signali — kamida (so'm)"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='correction_alert_pct',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Tuzatish signali — kunlik savdodan (%)'),
        ),
    ]
