# Generated by Django 5.1.5 on 2026-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemsettings_correction_alert_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='fine_penalty_percent',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='fine_high',
            field=models.PositiveBigIntegerField(default=20000000, verbose_name="Yuqori jarima (so'm)"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='fine_medium',
            field=models.PositiveBigIntegerField(default=10000000, verbose_name="O'rta jarima (so'm)"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='fine_small',
            field=models.PositiveBigIntegerField(default=5000000, verbose_name="Kichik jarima (so'm)"),
        ),
    ]
