# Generated by Django 5.1.5 on 2026-09-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_normalize_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='require_daily_close',
            field=models.BooleanField(default=True, verbose_name='Kun yakuni majburiy'),
        ),
    ]
