# Generated by Django 5.1.5 on 2026-09-11 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('number', models.CharField(max_length=20, verbose_name="Do'kon raqami")),
                ('stir', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='STIR')),
                ('owner_name', models.CharField(blank=True, max_length=200, verbose_name='Egasi')),
                ('owner_phone', models.CharField(blank=True, max_length=20, verbose_name='Egasi telefoni')),
                ('map_x', models.FloatField(blank=True, null=True)),
                ('map_y', models.FloatField(blank=True, null=True)),
                ('closed_weekdays', models.CharField(blank=True, max_length=20, verbose_name='Yopiq kunlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='catalog.shopcategory', verbose_name='Toifa')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='geo.market', verbose_name='Bozor')),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='geo.row', verbose_name='Qator')),
            ],
            options={
                'verbose_name': "Do'kon",
                'verbose_name_plural': "Do'konlar",
                'ordering': ['market', 'number'],
                'indexes': [models.Index(fields=['market', 'is_active'], name='shops_shop_market__38fefe_idx'), models.Index(fields=['stir'], name='shops_shop_stir_0119d3_idx')],
                'unique_together': {('market', 'number')},
            },
        ),
    ]
