# Generated by Django 5.1.5 on 2026-09-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_latitude_shop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Manzil'),
        ),
    ]
