# Generated by Django 5.1.5 on 2026-09-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='fiscal_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Kassa (FM/terminal) raqami'),
        ),
    ]
