# Generated by Django 5.1.5 on 2026-09-10 18:04

import cameras.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi/joyi')),
                ('rtsp_url', models.CharField(blank=True, max_length=500, verbose_name='RTSP manzil')),
                ('ingest_token', models.CharField(default=cameras.models.make_token, editable=False, max_length=64, unique=True, verbose_name='Ingest token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi signal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='markets.market', verbose_name='Bozor')),
                ('shops', models.ManyToManyField(blank=True, related_name='cameras', to='markets.shop', verbose_name="Qamrovdagi do'konlar")),
            ],
            options={
                'verbose_name': 'Kamera',
                'verbose_name_plural': 'Kameralar',
                'ordering': ['market', 'name'],
            },
        ),
    ]
