# Generated by Django 5.1.5 on 2026-09-10 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visited_at', models.DateTimeField(blank=True, null=True, verbose_name='Tashrif vaqti')),
                ('result', models.CharField(choices=[('confirmed', 'Tasdiqlandi (savdo yashirilgan)'), ('false_signal', "Noto'g'ri signal"), ('pending', 'Jarayonda')], default='pending', max_length=15, verbose_name='Natija')),
                ('act_number', models.CharField(blank=True, max_length=60, verbose_name='Dalolatnoma raqami')),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Jarima (so'm)")),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='analytics.alert')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='markets.shop')),
            ],
            options={
                'verbose_name': 'Tekshiruv',
                'verbose_name_plural': 'Tekshiruvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='inspections/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspection')),
            ],
        ),
    ]
