# Generated by Django 5.1.5 on 2026-09-11 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('message', models.TextField(verbose_name='Matn')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=12)),
                ('response', models.TextField(blank=True, verbose_name='Javob')),
            ],
            options={
                'verbose_name': "E'tiroz",
                'verbose_name_plural': "E'tirozlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('date', models.DateField(db_index=True)),
                ('truth_pct', models.PositiveSmallIntegerField(default=0, verbose_name='Rostlik %')),
                ('parts', models.JSONField(default=dict)),
                ('weakest', models.CharField(blank=True, max_length=20, verbose_name='Eng zaif qism')),
                ('entered_sales', models.BigIntegerField(default=0)),
                ('cash_amount', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kunlik ball',
                'verbose_name_plural': 'Kunlik ballar',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('result', models.CharField(choices=[('confirmed', 'Tasdiqlandi'), ('false', "Noto'g'ri signal"), ('pending', 'Jarayonda')], default='pending', max_length=12)),
                ('act_number', models.CharField(blank=True, max_length=60, verbose_name='Dalolatnoma')),
                ('fine_amount', models.BigIntegerField(blank=True, null=True, verbose_name="Jarima (so'm)")),
                ('photo', models.ImageField(blank=True, upload_to='inspections/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tekshiruv',
                'verbose_name_plural': 'Tekshiruvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('date', models.DateField(db_index=True)),
                ('median', models.BigIntegerField(default=0)),
                ('p25', models.BigIntegerField(default=0)),
                ('p75', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bozor narxi',
                'verbose_name_plural': 'Bozor narxlari',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('date', models.DateField()),
                ('level', models.CharField(choices=[('green', 'Yashil'), ('yellow', 'Sariq'), ('red', 'Qizil')], max_length=10)),
                ('reason', models.CharField(max_length=300, verbose_name='Sabab')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('assigned', 'Biriktirilgan'), ('resolved', 'Yakunlangan'), ('dismissed', "E'tiborsiz")], default='new', max_length=12)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signallar',
                'ordering': ['-created_at'],
            },
        ),
    ]
