# Generated by Django 5.1.5 on 2026-09-11 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('catalog', '0001_initial'),
        ('geo', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='analytics.alert'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeal',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='dailyscore',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='analytics.alert'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='geo.market'),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='catalog.productcategory'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='analytics_a_status_39105a_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['shop', 'date'], name='analytics_a_shop_id_dab22d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyscore',
            index=models.Index(fields=['shop', 'date'], name='analytics_d_shop_id_fe3ada_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyscore',
            index=models.Index(fields=['date', 'truth_pct'], name='analytics_d_date_88abc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyscore',
            unique_together={('shop', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together={('market', 'product_category', 'date')},
        ),
    ]
