# Generated by Django 5.1.5 on 2026-09-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('truth', 'Rostlik darajasi'), ('cash_shortage', 'Kassa kamomadi')], default='truth', max_length=16),
        ),
    ]
