# Generated by Django 5.1.5 on 2026-09-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alert_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('truth', 'Rostlik darajasi'), ('cash_mismatch', 'Kassa nomuvofiqligi'), ('zero_sales', 'Savdo kiritilmagan')], default='truth', max_length=16),
        ),
    ]
