# Generated by Django 5.1.5 on 2026-09-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_alert_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyscore',
            name='hidden_sales',
            field=models.BigIntegerField(default=0, verbose_name="Yashirilgan savdo (so'm)"),
        ),
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('truth', 'Rostlik darajasi'), ('cash_mismatch', 'Kassa nomuvofiqligi'), ('zero_sales', 'Savdo kiritilmagan'), ('anomaly', 'Savdo keskin tushdi')], default='truth', max_length=16),
        ),
    ]
