# Generated by Django 5.1.5 on 2026-09-24 16:22

from django.db import migrations, models


def fill_measured(apps, schema_editor):
    DailyScore = apps.get_model("analytics", "DailyScore")
    batch = []
    for ds in DailyScore.objects.only("id", "parts").iterator():
        m = any(v is not None for v in (ds.parts or {}).values())
        if m:
            batch.append(ds.id)
    DailyScore.objects.filter(id__in=batch).update(measured=True)


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_dailyscore_hidden_sales_alter_alert_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyscore',
            name='measured',
            field=models.BooleanField(db_index=True, default=False, verbose_name="O'lchangan"),
        ),
        migrations.RunPython(fill_measured, migrations.RunPython.noop),
    ]
