# Generated by Django 5.1.5 on 2026-09-25 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_cleanup_partial_day_alerts'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('kind', models.CharField(choices=[('fire', "Yong'in"), ('flood', 'Suv toshqini'), ('theft', "O'g'irlik"), ('collapse', 'Qulash / avariya'), ('other', 'Boshqa')], max_length=12, verbose_name='Turi')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name="Sodir bo'lgan vaqt")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Raqam')),
                ('snapshot', models.JSONField(default=dict)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('total_value', models.BigIntegerField(default=0, verbose_name='Jami ombor qiymati')),
                ('shops_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='geo.market')),
            ],
            options={
                'verbose_name': 'Favqulodda holat',
                'verbose_name_plural': 'Favqulodda holatlar',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
