# Generated by Django 5.1.5 on 2026-09-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('truth', 'Rostlik darajasi'), ('cash_mismatch', 'Kassa nomuvofiqligi'), ('zero_sales', 'Savdo kiritilmagan'), ('anomaly', 'Savdo keskin tushdi'), ('buyer_report', 'Xaridor xabari')], default='truth', max_length=16),
        ),
    ]
