# Generated by Django 5.1.5 on 2026-09-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_alert_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('truth', 'Rostlik darajasi'), ('cash_mismatch', 'Kassa nomuvofiqligi'), ('zero_sales', 'Savdo kiritilmagan'), ('anomaly', 'Savdo keskin tushdi'), ('buyer_report', 'Xaridor xabari'), ('gate_unrecorded', 'Hujjatsiz kirim')], default='truth', max_length=16),
        ),
    ]
