# Generated by Django 5.1.5 on 2026-09-26 16:25

from django.db import migrations, models


def fill_basis(apps, schema_editor):
    """Eski yozuvlar: kg/litr bilan sotiladigan toifa — shu birlik, qolgani dona."""
    MarketPrice = apps.get_model("analytics", "MarketPrice")
    for unit in ("kg", "litr"):
        MarketPrice.objects.filter(product_category__default_unit=unit).update(basis=unit)


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_alert_kind'),
        ('catalog', '0006_fill_variant_kind'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='basis',
            field=models.CharField(default='dona', max_length=40, verbose_name='Narx asosi'),
        ),
        migrations.RunPython(fill_basis, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together={('market', 'product_category', 'basis', 'date')},
        ),
    ]
