# Generated by Django 5.1.5 on 2026-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_market_price_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('truth', 'Rostlik darajasi'), ('cash_mismatch', 'Kassa nomuvofiqligi'), ('zero_sales', 'Savdo kiritilmagan'), ('anomaly', 'Savdo keskin tushdi'), ('buyer_report', 'Xaridor xabari'), ('gate_unrecorded', 'Hujjatsiz kirim'), ('writeoff_over', "Hisobdan chiqarish me'yordan ko'p")], default='truth', max_length=16),
        ),
    ]
