# Generated by Django 5.1.5 on 2026-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_alter_alert_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='fine_level',
            field=models.CharField(blank=True, choices=[('small', 'Kichik'), ('medium', "O'rta"), ('high', 'Yuqori')], max_length=8, verbose_name='Jarima darajasi'),
        ),
    ]
