# Generated by Django 5.1.5 on 2026-09-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('litr', 'litr'), ('metr', 'metr'), ('quti', 'quti')], default='dona', max_length=10, verbose_name='Birlik')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Barkod')),
                ('buy_price', models.BigIntegerField(default=0, verbose_name="Tannarx (so'm)")),
                ('sell_price', models.BigIntegerField(default=0, verbose_name="Sotish narxi (so'm)")),
                ('pack_coeff', models.DecimalField(decimal_places=3, default=1, help_text='1 qop = necha birlik', max_digits=10, verbose_name='Qadoq koeffitsienti')),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Kam qoldiq chegarasi')),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Joriy qoldiq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Mahsulot toifasi')),
                ('default_unit', models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('litr', 'litr'), ('metr', 'metr'), ('quti', 'quti')], default='dona', max_length=10, verbose_name='Birlik')),
                ('waste_norm_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name="Chirish me'yori (%)")),
            ],
            options={
                'verbose_name': 'Mahsulot toifasi',
                'verbose_name_plural': 'Mahsulot toifalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name="Do'kon toifasi")),
            ],
            options={
                'verbose_name': "Do'kon toifasi",
                'verbose_name_plural': "Do'kon toifalari",
                'ordering': ['name'],
            },
        ),
    ]
