# Generated by Django 5.1.5 on 2026-09-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('qop', 'qop'), ("bog'lam", "bog'lam"), ('litr', 'litr'), ('metr', 'metr'), ('quti', 'quti')], default='dona', max_length=10, verbose_name='Birlik'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='default_unit',
            field=models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('qop', 'qop'), ("bog'lam", "bog'lam"), ('litr', 'litr'), ('metr', 'metr'), ('quti', 'quti')], default='dona', max_length=10, verbose_name='Birlik'),
        ),
    ]
