# Generated by Django 5.1.5 on 2026-09-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=40, verbose_name='Rang'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name="O'lcham"),
        ),
    ]
