# Generated by Django 5.1.5 on 2026-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='variant_kind',
            field=models.CharField(choices=[('none', 'Variantsiz'), ('clothing', "Kiyim o'lchami (XS–3XL, 42–60)"), ('shoes', "Poyabzal o'lchami (35–46)"), ('kids', "Bolalar kiyimi (bo'y, sm)"), ('headwear', "Bosh kiyim o'lchami (52–62)"), ('socks', "Paypoq o'lchami (35-37...)"), ('pack_weight', "Qadoq og'irligi (g, kg)"), ('pack_volume', 'Qadoq hajmi (ml, L)'), ('type', 'Turi / modeli'), ('color', 'Faqat rang')], default='none', max_length=16, verbose_name='Variant turi'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='variant_options',
            field=models.CharField(blank=True, help_text="Vergul bilan, masalan: 100 g, 250 g, 1 kg. Bo'sh — turning umumiy ro'yxati.", max_length=300, verbose_name='Tayyor variantlar'),
        ),
    ]
