# Generated by Django 5.1.5 on 2026-09-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_waste_norm_by_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='buyer_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Bo'sh — umumiy sozlama", max_digits=4, null=True, verbose_name='Xaridorga aylanish ulushi'),
        ),
    ]
