# Generated by Django 5.1.5 on 2026-09-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('amount', models.BigIntegerField(default=0, verbose_name="Summa (so'm)")),
                ('source', models.CharField(choices=[('excel', 'Excel import'), ('tax_api', 'Soliq API'), ('kassa', 'Virtual kassa')], default='excel', max_length=12, verbose_name='Manba')),
            ],
            options={
                'verbose_name': 'Kassa/Deklaratsiya',
                'verbose_name_plural': 'Kassa/Deklaratsiya',
            },
        ),
    ]
