# Generated by Django 5.1.5 on 2026-09-11 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_records', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='cashrecord',
            index=models.Index(fields=['shop', 'date'], name='cash_cashre_shop_id_a43032_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cashrecord',
            unique_together={('shop', 'date', 'source')},
        ),
    ]
