# Generated by Django 5.1.5 on 2026-09-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('source', models.CharField(choices=[('excel', 'Excel import'), ('tax_api', 'Soliq API'), ('kassa', 'Virtual kassa')], max_length=12)),
                ('adapter', models.CharField(blank=True, max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('fetched', models.PositiveIntegerField(default=0)),
                ('saved', models.PositiveIntegerField(default=0)),
                ('unmatched', models.PositiveIntegerField(default=0)),
                ('problems', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Deklaratsiya sinxronlash',
                'verbose_name_plural': 'Deklaratsiya sinxronlash',
                'ordering': ['-created_at'],
            },
        ),
    ]
