# Generated by Django 5.2.17 on 2026-10-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash", "0003_declarationsync"),
        ("shops", "0004_shop_fiscal_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Yaratilgan")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Yangilangan")),
                ("source", models.CharField(choices=[("excel", "Excel import"), ("tax_api", "Soliq API"), ("kassa", "Virtual kassa")], max_length=12, verbose_name="Manba")),
                ("source_receipt_id", models.CharField(help_text="Tashqi tizimdagi barqaror, takrorlanmaydigan chek identifikatori.", max_length=128, verbose_name="Manbadagi chek ID")),
                ("fiscal_number", models.CharField(blank=True, max_length=100, verbose_name="Fiskal raqam")),
                ("issued_at", models.DateTimeField(db_index=True, verbose_name="Chek vaqti")),
                ("status", models.CharField(choices=[("issued", "Rasmiylashtirilgan"), ("returned", "Qaytarish cheki"), ("cancelled", "Bekor qilingan")], default="issued", max_length=12, verbose_name="Holat")),
                ("total", models.BigIntegerField(default=0, verbose_name="Chek jami (so'm)")),
                ("raw_payload", models.JSONField(blank=True, default=dict, help_text="Manba formatini keyin tekshirish uchun o'zgartirilmagan javob.", verbose_name="Manba javobi")),
                ("original_receipt", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="return_receipts", to="cash.fiscalreceipt", verbose_name="Asl chek")),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fiscal_receipts", to="shops.shop")),
            ],
            options={"verbose_name": "Fiskal chek", "verbose_name_plural": "Fiskal cheklar", "ordering": ["-issued_at", "-id"]},
        ),
        migrations.CreateModel(
            name="FiscalReceiptLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_number", models.PositiveIntegerField(verbose_name="Qator raqami")),
                ("product_name", models.CharField(max_length=300, verbose_name="Mahsulot nomi")),
                ("product_code", models.CharField(blank=True, max_length=128, verbose_name="Mahsulot kodi")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12, verbose_name="Miqdor")),
                ("unit_price", models.BigIntegerField(default=0, verbose_name="Birlik narxi (so'm)")),
                ("line_total", models.BigIntegerField(default=0, verbose_name="Qator jami (so'm)")),
                ("receipt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="cash.fiscalreceipt")),
            ],
            options={"verbose_name": "Fiskal chek qatori", "verbose_name_plural": "Fiskal chek qatorlari", "ordering": ["line_number", "id"]},
        ),
        migrations.AddConstraint(model_name="fiscalreceipt", constraint=models.UniqueConstraint(fields=("source", "source_receipt_id"), name="uniq_fiscal_receipt_source_id")),
        migrations.AddIndex(model_name="fiscalreceipt", index=models.Index(fields=["shop", "issued_at"], name="cash_fiscal_shop_id_a2497d_idx")),
        migrations.AddIndex(model_name="fiscalreceipt", index=models.Index(fields=["status", "issued_at"], name="cash_fiscal_status_0c04f3_idx")),
        migrations.AddConstraint(model_name="fiscalreceiptline", constraint=models.UniqueConstraint(fields=("receipt", "line_number"), name="uniq_fiscal_receipt_line")),
    ]
