# Generated by Django 5.1.5 on 2026-10-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_fiscalreceipt_fiscalreceiptline'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fiscalreceipt',
            new_name='cash_fiscal_shop_id_9de650_idx',
            old_name='cash_fiscal_shop_id_a2497d_idx',
        ),
        migrations.RenameIndex(
            model_name='fiscalreceipt',
            new_name='cash_fiscal_status_715f9b_idx',
            old_name='cash_fiscal_status_0c04f3_idx',
        ),
    ]
