# Generated by Django 5.1.5 on 2026-09-11 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Viloyat')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Kod')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=200, verbose_name='Bozor')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='geo.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Bozor',
                'verbose_name_plural': 'Bozorlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('label', models.CharField(max_length=60, verbose_name='Qator')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='geo.market', verbose_name='Bozor')),
            ],
            options={
                'verbose_name': 'Qator',
                'verbose_name_plural': 'Qatorlar',
                'ordering': ['market', 'order', 'label'],
                'unique_together': {('market', 'label')},
            },
        ),
    ]
